// <auto-generated />
namespace TnpdModels.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addSMSGuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSMSGuid));
        
        string IMigrationMetadata.Id
        {
            get { return "202008231229241_addSMSGuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
