// <auto-generated />
namespace TnpdModels.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BigBinnerLink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BigBinnerLink));
        
        string IMigrationMetadata.Id
        {
            get { return "202004210220546_BigBinnerLink"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
