// <auto-generated />
namespace TnpdModels.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addCaseFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCaseFile));
        
        string IMigrationMetadata.Id
        {
            get { return "202211081005428_addCaseFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
