// <auto-generated />
namespace TnpdModels.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addTrafficViolationItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTrafficViolationItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202204070909000_addTrafficViolationItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
